// [UNITY-SKILL:SPRITEATLAS]
// [TYPE:POSTPROCESS-ADDRESSABLES]
// Generated by SpriteAtlas V2 Skill
// This script builds Addressables content after atlas generation

using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

#if UNITY_ADDRESSABLES
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEditor.AddressableAssets.Build;
#endif

public class BuildAddressablesPostprocess : IPostprocessBuildWithReport
{
    public int callbackOrder => 1;

    public void OnPostprocessBuild(BuildReport report)
    {
#if UNITY_ADDRESSABLES
        Debug.Log("[Addressables] Building Addressables content for Sprite Atlases...");

        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null) return;

        try
        {
            AddressableAssetSettings.BuildPlayerContent(out AddressablesPlayerBuildResult result);
            if (!string.IsNullOrEmpty(result.Error))
                Debug.LogError($"[Addressables] Build failed: {result.Error}");
        }
        catch (System.Exception ex)
        {
            Debug.LogError($"[Addressables] Build exception: {ex.Message}");
        }
#endif
    }
}
