// [UNITY-SKILL:SPRITEATLAS]
// [TYPE:PREBUILD]
// Generated by SpriteAtlas V2 Skill
// This script automatically generates SpriteAtlas assets during prebuild

using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.U2D;
using UnityEngine;
using UnityEngine.U2D;
using System.Linq;
using System.Collections.Generic;

#if UNITY_ADDRESSABLES
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
#endif

public class SpriteAtlasPrebuildGenerator : IPreprocessBuildWithReport
{
    public int callbackOrder => 0;

    private List<string> generatedAtlasPaths = new List<string>();

    public void OnPreprocessBuild(BuildReport report)
    {
        Debug.Log("[SpriteAtlas] Generating atlases for late-binding via Addressables...");

        // CRITICAL: Enable Sprite Packer mode
        EditorSettings.spritePackerMode = SpritePackerMode.SpriteAtlasV2;

        generatedAtlasPaths.Clear();

        // Categorize project sprites into atlases
        // includeInBuild is FALSE for Addressables delivery
        GenerateAtlasByFolder("Assets/_Project/Animations", "Assets/_Project/Atlases/Lord_Animations.spriteatlasv2", includeInBuild: false);
        GenerateAtlasByFolder("Assets/_Project/Prefabs", "Assets/_Project/Atlases/Lord_Common.spriteatlasv2", includeInBuild: false);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        // Setup Addressables for all generated atlases
        SetupAddressables();
    }

    private void SetupAddressables()
    {
#if UNITY_ADDRESSABLES
        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
        {
            Debug.LogError("[SpriteAtlas] Addressables is not initialized. Please install and setup Addressables package.");
            return;
        }

        var group = settings.DefaultGroup;
        if (group == null)
        {
            Debug.LogError("[SpriteAtlas] Default Addressables group not found.");
            return;
        }

        foreach (var atlasPath in generatedAtlasPaths)
        {
            var guid = AssetDatabase.AssetPathToGUID(atlasPath);
            if (string.IsNullOrEmpty(guid))
            {
                Debug.LogWarning($"[SpriteAtlas] Could not find GUID for {atlasPath}");
                continue;
            }

            string atlasName = System.IO.Path.GetFileNameWithoutExtension(atlasPath);

            // Check if already exists
            var existingEntry = settings.FindAssetEntry(guid);
            if (existingEntry != null)
            {
                // Ensure address matches filename
                if (existingEntry.address != atlasName)
                {
                    existingEntry.address = atlasName;
                }
                continue;
            }

            // Create addressable entry
            var entry = settings.CreateOrMoveEntry(guid, group, false, false);
            entry.address = atlasName; // Use atlas name as address

            Debug.Log($"[SpriteAtlas] Added to Addressables: {atlasName} at {atlasPath}");
        }

        settings.SetDirty(AddressableAssetSettings.ModificationEvent.EntryAdded, null, true);
#else
        Debug.LogError("[SpriteAtlas] Addressables package is not installed. Please install 'com.unity.addressables' package.");
#endif
    }

    private bool IsValidProjectSprite(string assetPath)
    {
        return assetPath.StartsWith("Assets/") && !assetPath.Contains("/Packages/");
    }

    private void GenerateAtlasByFolder(string spriteFolder, string atlasPath, bool includeInBuild)
    {
        if (!AssetDatabase.IsValidFolder(spriteFolder)) return;

        string[] guids = AssetDatabase.FindAssets("t:Sprite", new[] { spriteFolder });
        Object[] sprites = guids
            .Select(g => AssetDatabase.GUIDToAssetPath(g))
            .Where(path => IsValidProjectSprite(path))
            .Select(path => AssetDatabase.LoadAssetAtPath<Sprite>(path))
            .Where(s => s != null)
            .Cast<Object>()
            .ToArray();

        if (sprites.Length == 0) return;

        SpriteAtlasAsset atlasAsset;
        if (System.IO.File.Exists(atlasPath))
        {
            atlasAsset = SpriteAtlasAsset.Load(atlasPath);
            var spriteAtlas = AssetDatabase.LoadAssetAtPath<SpriteAtlas>(atlasPath);
            if (spriteAtlas != null)
                atlasAsset.Remove(spriteAtlas.GetPackables());
        }
        else
        {
            atlasAsset = new SpriteAtlasAsset();
            string dir = System.IO.Path.GetDirectoryName(atlasPath);
            if (!System.IO.Directory.Exists(dir)) System.IO.Directory.CreateDirectory(dir);
        }

        atlasAsset.Add(sprites);
        SpriteAtlasAsset.Save(atlasAsset, atlasPath);
        AssetDatabase.ImportAsset(atlasPath);

        ConfigureAtlasImporter(atlasPath, includeInBuild);
        generatedAtlasPaths.Add(atlasPath);
    }

    private void ConfigureAtlasImporter(string atlasPath, bool includeInBuild)
    {
        SpriteAtlasImporter importer = AssetImporter.GetAtPath(atlasPath) as SpriteAtlasImporter;
        if (importer == null) return;

        var textureSettings = importer.textureSettings;
        textureSettings.filterMode = FilterMode.Point; // For stylized/pixel art
        textureSettings.generateMipMaps = false;
        importer.textureSettings = textureSettings;

        var packingSettings = importer.packingSettings;
        packingSettings.padding = 4;
        packingSettings.enableAlphaDilation = true;
        importer.packingSettings = packingSettings;

        importer.includeInBuild = includeInBuild;
        importer.SaveAndReimport();
    }
}
