// [UNITY-SKILL:SPRITEATLAS]
// [TYPE:PREBUILD]
// Generated by SpriteAtlas V2 Skill
//
// 이 프로젝트의 아틀라스는 손으로 구성된(hand-composed) 상태이므로,
// 폴더 기반으로 재생성하지 않고 "빌드 설정만 강제(enforce)" 합니다.
//  - includeInBuild = false  → 어드레서블 late-binding 전달 (빌드 중복 제거)
//  - 어드레서블 엔트리 보장   → address = 아틀라스 이름(=아틀라스 태그)
// SpriteAtlasManager.atlasRequested → SpriteAtlasLateBinding 이 런타임 로드를 담당합니다.

using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.U2D;
using UnityEngine;

#if UNITY_ADDRESSABLES
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
#endif

public class SpriteAtlasPrebuildGenerator : IPreprocessBuildWithReport
{
    public int callbackOrder => 0;

    // 프로젝트의 실제 아틀라스가 위치한 폴더 (구성은 보존, 설정만 강제)
    private const string AtlasFolder = "Assets/_Project/ResourcceEX/Atlases";

    public void OnPreprocessBuild(BuildReport report)
    {
        Debug.Log("[SpriteAtlas] Enforcing late-binding settings on existing atlases...");

        // V2 스프라이트 패킹 보장
        EditorSettings.spritePackerMode = SpritePackerMode.SpriteAtlasV2;

        if (!AssetDatabase.IsValidFolder(AtlasFolder))
        {
            Debug.LogWarning($"[SpriteAtlas] Atlas folder not found: {AtlasFolder}");
            return;
        }

        // 폴더 내 모든 SpriteAtlas (v2) 에 includeInBuild=false 강제 + 어드레서블 등록
        string[] guids = AssetDatabase.FindAssets("t:SpriteAtlas", new[] { AtlasFolder });
        foreach (var guid in guids)
        {
            string atlasPath = AssetDatabase.GUIDToAssetPath(guid);
            EnforceLateBinding(atlasPath);
            EnsureAddressable(atlasPath, guid);
        }

        AssetDatabase.SaveAssets();
    }

    /// <summary>아틀라스를 어드레서블 전달용으로 강제 — includeInBuild=false.</summary>
    private void EnforceLateBinding(string atlasPath)
    {
        var importer = AssetImporter.GetAtPath(atlasPath) as SpriteAtlasImporter;
        if (importer == null) return;

        if (importer.includeInBuild)
        {
            importer.includeInBuild = false;
            importer.SaveAndReimport();
            Debug.Log($"[SpriteAtlas] includeInBuild=false enforced: {atlasPath}");
        }
    }

    /// <summary>아틀라스가 어드레서블 엔트리로 등록되어 있고 address=아틀라스 이름인지 보장.</summary>
    private void EnsureAddressable(string atlasPath, string guid)
    {
#if UNITY_ADDRESSABLES
        var settings = AddressableAssetSettingsDefaultObject.Settings;
        if (settings == null)
        {
            Debug.LogError("[SpriteAtlas] Addressables is not initialized.");
            return;
        }

        string atlasName = System.IO.Path.GetFileNameWithoutExtension(atlasPath);

        var existing = settings.FindAssetEntry(guid);
        if (existing != null)
        {
            if (existing.address != atlasName) existing.address = atlasName;
            return;
        }

        var group = settings.DefaultGroup;
        if (group == null)
        {
            Debug.LogError("[SpriteAtlas] Default Addressables group not found.");
            return;
        }

        var entry = settings.CreateOrMoveEntry(guid, group, false, false);
        entry.address = atlasName; // 어드레서블 주소 = 아틀라스 태그 (late-binding 매칭)
        settings.SetDirty(AddressableAssetSettings.ModificationEvent.EntryAdded, entry, true);
        Debug.Log($"[SpriteAtlas] Registered to Addressables: {atlasName}");
#else
        Debug.LogError("[SpriteAtlas] Addressables package not installed.");
#endif
    }
}
