// [UNITY-SKILL:SPRITEATLAS]
// [TYPE:RUNTIME-LOADER]
// Generated by SpriteAtlas Skill
// This script handles late-binding atlas loading via Addressables

using UnityEngine;
using UnityEngine.U2D;
using System.Collections.Generic;

#if UNITY_ADDRESSABLES
using UnityEngine.AddressableAssets;
using UnityEngine.ResourceManagement.AsyncOperations;
#endif

public class SpriteAtlasLateBinding : MonoBehaviour
{
    private static SpriteAtlasLateBinding instance;

#if UNITY_ADDRESSABLES
    private Dictionary<string, AsyncOperationHandle<SpriteAtlas>> loadedAtlases = new Dictionary<string, AsyncOperationHandle<SpriteAtlas>>();
#endif

    void Awake()
    {
        if (instance != null && instance != this)
        {
            Destroy(gameObject);
            return;
        }

        instance = this;
        DontDestroyOnLoad(gameObject);

        SpriteAtlasManager.atlasRequested += OnAtlasRequested;
    }

    void OnDestroy()
    {
        SpriteAtlasManager.atlasRequested -= OnAtlasRequested;

#if UNITY_ADDRESSABLES
        foreach (var handle in loadedAtlases.Values)
        {
            if (handle.IsValid()) Addressables.Release(handle);
        }
        loadedAtlases.Clear();
#endif
    }

    private void OnAtlasRequested(string tag, System.Action<SpriteAtlas> callback)
    {
#if UNITY_ADDRESSABLES
        if (loadedAtlases.ContainsKey(tag))
        {
            var handle = loadedAtlases[tag];
            if (handle.IsDone && handle.Status == AsyncOperationStatus.Succeeded)
            {
                callback(handle.Result);
                return;
            }
        }

        Debug.Log($"[SpriteAtlas] Loading atlas via Addressables: {tag}");
        var loadHandle = Addressables.LoadAssetAsync<SpriteAtlas>(tag);
        loadedAtlases[tag] = loadHandle;

        loadHandle.Completed += (handle) =>
        {
            if (handle.Status == AsyncOperationStatus.Succeeded)
            {
                Debug.Log($"[SpriteAtlas] Successfully loaded atlas: {tag}");
                callback(handle.Result);
            }
            else
            {
                Debug.LogError($"[SpriteAtlas] Failed to load atlas: {tag}");
            }
        };
#else
        Debug.LogError($"[SpriteAtlas] Addressables package not installed. Cannot load atlas: {tag}");
        callback(null);
#endif
    }
}
